###
GET http://localhost:8000/getAllCustomers

###
GET http://localhost:8000/getAllCustomers
Content-Type: application/xml

###
GET http://localhost:8000/getCustomerById/2

###
GET http://localhost:8000/getCustomerById/1
Content-Type: application/xml

###
POST http://localhost:8000/customer
Accept: application/json

{
    "customer_id": "3",
    "full_name": "Virendra Nath Behl",
    "city": "Lucknow",
    "phone": "80043xxxxx"
}